### ISSUE TITLE
Call REST with parameters ?

### ISSUE THREAD

**Issue by delonleonard** [kserve/rest-proxy#13]
hi,

May i check if it is possible to include parameters in the JSON schema ? I think it will return `unmarshalerDecoder` Is it possible to include it as part of the unit test in [marshaler_test.go](https://github.com/kserve/rest-proxy/blob/main/proxy/marshaler_test.go). Thanks for the great work.

```json
	{
		"id": "1",
		"inputs": [{
			"name": "input:0",
			"shape": [-1, -1, -1, -1],
			"datatype": "UINT8",
			"parameters": {
				"binary_data_size": {
					"int64Param": 100
				}
			}
		}]
	}
```

Seems like it cannot parse parameters properly ?
```
{1 map[] [name:"input:0"  datatype:"UINT8"  shape:-1  shape:-1  shape:-1  shape:-1  parameters:{key:"binary_data_size"  value:{}}] []}
```

Do you have any advise on this issue please ?. Thank you.

**Comment by njhill** [comment]
@delonleonard sorry for not noticing this until just now. I think you're right that it's a bug and that parameters should have additional handling in the marshaler. You're right that it would be best to start with some extra test(s) for this.

I'd be happy to review if you're interested in contributing a test/fix, or I'll try to do it when I get a chance.

By the way, I think in your example the json would just look like:
```json
			"parameters": {
				"binary_data_size": 100
			}
```
but would be converted to/from the appropriate protobuf `oneof` field implicitly based on the json type (string/int/bool is unambiguous).

**Comment by njhill** [comment]
@delonleonard FYI this has now been fixed in the latest version.
