### ISSUE TITLE
Move to Go 1.21 (to be consistent with KServe v0.12)

### ISSUE THREAD

**Issue by ckadner** [kserve/rest-proxy#38]
When we upgrade our Go module dependencies to `kserve v0.12.0` we will need to upgrade to Go 1.21 which requires updating many other dependencies (some with breaking API changes).

And we will need to revert our Docker builds to install Go and Go tooling into a UBI base images as opposed to using the UBI go-toolset image, as the latest UBI/go-toolset image support goes up to Go version 1.20 only. Based on the release cadence of recent past, a UBI/go-toolset:1.21 may not be available for at least a few months.

**Comment by spolti** [comment]
The gotool-set 1.20 was released a few days ago.

**Comment by ckadner** [comment]
And [1.21](https://catalog.redhat.com/software/containers/ubi9/go-toolset/61e5c00b4ec9945c18787690?architecture=amd64&image=6644a7b66e80d90a600c71fe) 😄

**Comment by spolti** [comment]
Go lang is 1.21. Closing.
